In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 50)

In [ ]:
df = pd.read_csv('/content/sample_data/ds_salaries.csv')
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [ ]:
print(f'Shape: {df.shape}')

Shape: (607, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [ ]:
df['job_title'].unique()

array(['Data Scientist', 'Machine Learning Scientist',
       'Big Data Engineer', 'Product Data Analyst',
       'Machine Learning Engineer', 'Data Analyst', 'Lead Data Scientist',
       'Business Data Analyst', 'Lead Data Engineer', 'Lead Data Analyst',
       'Data Engineer', 'Data Science Consultant', 'BI Data Analyst',
       'Director of Data Science', 'Research Scientist',
       'Machine Learning Manager', 'Data Engineering Manager',
       'Machine Learning Infrastructure Engineer', 'ML Engineer',
       'AI Scientist', 'Computer Vision Engineer',
       'Principal Data Scientist', 'Data Science Manager', 'Head of Data',
       '3D Computer Vision Researcher', 'Data Analytics Engineer',
       'Applied Data Scientist', 'Marketing Data Analyst',
       'Cloud Data Engineer', 'Financial Data Analyst',
       'Computer Vision Software Engineer',
       'Director of Data Engineering', 'Data Science Engineer',
       'Principal Data Engineer', 'Machine Learning Developer',
       'Applied Machine Learning Scientist', 'Data Analytics Manager',
       'Head of Data Science', 'Data Specialist', 'Data Architect',
       'Finance Data Analyst', 'Principal Data Analyst',
       'Big Data Architect', 'Staff Data Scientist', 'Analytics Engineer',
       'ETL Developer', 'Head of Machine Learning', 'NLP Engineer',
       'Lead Machine Learning Engineer', 'Data Analytics Lead'],
      dtype=object)

In [ ]:
df['job_title'].value_counts()

job_title
Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Machine Learning Scientist                    8
Big Data Engineer                             8
Director of Data Science                      7
AI Scientist                                  7
Principal Data Scientist                      7
Data Science Consultant                       7
Data Analytics Manager                        7
BI Data Analyst                               6
Computer Vision Engineer                      6
ML Engineer                                   6
Lead Data Engineer                            6
Applied Data Scientist                        5
Business Data Analyst                         5
Data Engineering Manager                      5
Head of Data                                  5
Data Analytics Engineer                       4
Head of Data Science                          4
Applied Machine Learning Scientist            4
Analytics Engineer                            4
Machine Learning Developer                    3
Data Science Engineer                         3
Lead Data Analyst                             3
Machine Learning Infrastructure Engineer      3
Lead Data Scientist                           3
Principal Data Engineer                       3
Computer Vision Software Engineer             3
Product Data Analyst                          2
ETL Developer                                 2
Cloud Data Engineer                           2
Financial Data Analyst                        2
Director of Data Engineering                  2
Principal Data Analyst                        2
Machine Learning Manager                      1
Marketing Data Analyst                        1
3D Computer Vision Researcher                 1
Finance Data Analyst                          1
Data Specialist                               1
Staff Data Scientist                          1
Big Data Architect                            1
Head of Machine Learning                      1
NLP Engineer                                  1
Lead Machine Learning Engineer                1
Data Analytics Lead                           1
Name: count, dtype: int64

In [ ]:
df['job_title'].nunique()

50

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("/content/sample_data/ds_salaries.csv")

# Grouping function
def group_job(title):
    title = str(title).lower().strip()

    # 1. Management / Leadership
    if "manager" in title or "director" in title or "head" in title:
        return "Management"

    # 2. Machine Learning / AI
    elif (
        "machine learning" in title
        or title == "ml engineer"
        or "ai" in title
        or "computer vision" in title
        or "nlp" in title
    ):
        return "ML_AI"

    # 3. Data Engineering
    elif (
        "data engineer" in title
        or "big data engineer" in title
        or "etl" in title
        or "architect" in title
        or "analytics engineer" in title
        or "data analytics engineer" in title
        or "cloud data engineer" in title
    ):
        return "Data_Engineering"

    # 4. Data Analysis
    elif "analyst" in title or "analytics lead" in title:
        return "Data_Analysis"

    # 5. Data Science
    elif "scientist" in title or "data science consultant" in title or "data science engineer" in title:
        return "Data_Science"

    # 6. Other
    else:
        return "Other"

# Create grouped column
df["job_group"] = df["job_title"].apply(group_job)

# Check grouping
print(df[["job_title", "job_group"]].head(20))
print(df["job_group"].value_counts())

# One-hot encode grouped column
df = pd.get_dummies(df, columns=["job_group"], drop_first=False)
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)
# Check result
print(df.head())
print(df.columns)

                     job_title         job_group
0               Data Scientist      Data_Science
1   Machine Learning Scientist             ML_AI
2            Big Data Engineer  Data_Engineering
3         Product Data Analyst     Data_Analysis
4    Machine Learning Engineer             ML_AI
5                 Data Analyst     Data_Analysis
6          Lead Data Scientist      Data_Science
7               Data Scientist      Data_Science
8        Business Data Analyst     Data_Analysis
9           Lead Data Engineer  Data_Engineering
10              Data Scientist      Data_Science
11              Data Scientist      Data_Science
12              Data Scientist      Data_Science
13           Lead Data Analyst     Data_Analysis
14                Data Analyst     Data_Analysis
15                Data Analyst     Data_Analysis
16               Data Engineer  Data_Engineering
17           Big Data Engineer  Data_Engineering
18     Data Science Consultant      Data_Science
19          Lead Data Engineer  Data_Engineering
job_group
Data_Science        185
Data_Engineering    173
Data_Analysis       120
ML_AI                84
Management           44
Other                 1
Name: count, dtype: int64
   Unnamed: 0  work_year experience_level employment_type  \
0           0       2020               MI              FT
1           1       2020               SE              FT
2           2       2020               SE              FT
3           3       2020               MI              FT
4           4       2020               SE              FT

                    job_title  salary salary_currency  salary_in_usd  \
0              Data Scientist   70000             EUR          79833
1  Machine Learning Scientist  260000             USD         260000
2           Big Data Engineer   85000             GBP         109024
3        Product Data Analyst   20000             USD          20000
4   Machine Learning Engineer  150000             USD         150000

  employee_residence  remote_ratio company_location company_size  \
0                 DE             0               DE            L
1                 JP             0               JP            S
2                 GB            50               GB            M
3                 HN             0               HN            S
4                 US            50               US            L

   job_group_Data_Analysis  job_group_Data_Engineering  \
0                        0                           0
1                        0                           0
2                        0                           1
3                        1                           0
4                        0                           0

   job_group_Data_Science  job_group_ML_AI  job_group_Management  \
0                       1                0                     0
1                       0                1                     0
2                       0                0                     0
3                       0                0                     0
4                       0                1                     0

   job_group_Other
0                0
1                0
2                0
3                0
4                0
Index(['Unnamed: 0', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size', 'job_group_Data_Analysis', 'job_group_Data_Engineering',
       'job_group_Data_Science', 'job_group_ML_AI', 'job_group_Management',
       'job_group_Other'],
      dtype='object')

In [ ]:
df = df.drop(columns=["job_title"])

In [ ]:
df = df.drop(columns=["Unnamed: 0"])

In [ ]:
df = df.drop(columns=["salary", "salary_currency"])

In [ ]:
# Get top 8 most frequent company locations
top_8_locations = df["company_location"].value_counts().head(8).index

# Map others to "Other"
df["company_location_grouped"] = df["company_location"].apply(
    lambda x: x if x in top_8_locations else "Other"
)

# One-hot encode
df = pd.get_dummies(df, columns=["company_location_grouped"], dtype=int)


# Check result
print(df.head())
print(df.columns)

   work_year experience_level employment_type  salary_in_usd  \
0       2020               MI              FT          79833
1       2020               SE              FT         260000
2       2020               SE              FT         109024
3       2020               MI              FT          20000
4       2020               SE              FT         150000

  employee_residence  remote_ratio company_location company_size  \
0                 DE             0               DE            L
1                 JP             0               JP            S
2                 GB            50               GB            M
3                 HN             0               HN            S
4                 US            50               US            L

   job_group_Data_Analysis  job_group_Data_Engineering  \
0                        0                           0
1                        0                           0
2                        0                           1
3                        1                           0
4                        0                           0

   job_group_Data_Science  job_group_ML_AI  job_group_Management  \
0                       1                0                     0
1                       0                1                     0
2                       0                0                     0
3                       0                0                     0
4                       0                1                     0

   job_group_Other  company_location_grouped_CA  company_location_grouped_DE  \
0                0                            0                            1
1                0                            0                            0
2                0                            0                            0
3                0                            0                            0
4                0                            0                            0

   company_location_grouped_ES  company_location_grouped_FR  \
0                            0                            0
1                            0                            0
2                            0                            0
3                            0                            0
4                            0                            0

   company_location_grouped_GB  company_location_grouped_GR  \
0                            0                            0
1                            0                            0
2                            1                            0
3                            0                            0
4                            0                            0

   company_location_grouped_IN  company_location_grouped_Other  \
0                            0                               0
1                            0                               1
2                            0                               0
3                            0                               1
4                            0                               0

   company_location_grouped_US
0                            0
1                            0
2                            0
3                            0
4                            1
Index(['work_year', 'experience_level', 'employment_type', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size', 'job_group_Data_Analysis', 'job_group_Data_Engineering',
       'job_group_Data_Science', 'job_group_ML_AI', 'job_group_Management',
       'job_group_Other', 'company_location_grouped_CA',
       'company_location_grouped_DE', 'company_location_grouped_ES',
       'company_location_grouped_FR', 'company_location_grouped_GB',
       'company_location_grouped_GR', 'company_location_grouped_IN',
       'company_location_grouped_Other', 'company_location_grouped_US'],
      dtype='object')

In [ ]:
print(df["company_location_grouped_US"].value_counts())

company_location_grouped_US
1    355
0    252
Name: count, dtype: int64

In [ ]:
df = df.drop(columns=["company_location"])

In [ ]:
df = df.drop(columns=["employee_residence"])

In [ ]:
# Encode experience_level (ordinal)
experience_map = {
    "EN": 0,
    "MI": 1,
    "SE": 2,
    "EX": 3
}
df["experience_level"] = df["experience_level"].map(experience_map)

# Encode company_size (ordinal)
size_map = {
    "S": 0,
    "M": 1,
    "L": 2
}
df["company_size"] = df["company_size"].map(size_map)
df["salary_in_usd"] = np.log1p(df["salary_in_usd"])

# One-hot encode employment_type
df = pd.get_dummies(df, columns=["employment_type"], drop_first=False)

# Convert booleans to 0/1 if needed
bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold, cross_validate, cross_val_predict
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
X = df.drop(columns=["salary_in_usd"])
y = df["salary_in_usd"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (607, 23)
y shape: (607,)

In [ ]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [ ]:
kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [ ]:
scoring = {
    "mae": "neg_mean_absolute_error",
    "mse": "neg_mean_squared_error",
    "rmse": "neg_root_mean_squared_error",
    "r2": "r2"
}

In [ ]:
cv_results = cross_validate(
    estimator=rf_model,
    X=X,
    y=y,
    cv=kf,
    scoring=scoring,
    return_train_score=True,
    n_jobs=-1
)

In [ ]:
results_df = pd.DataFrame({
    "Fold": range(1, 6),
    "Train MAE": -cv_results["train_mae"],
    "Validation MAE": -cv_results["test_mae"],
    "Train MSE": -cv_results["train_mse"],
    "Validation MSE": -cv_results["test_mse"],
    "Train RMSE": -cv_results["train_rmse"],
    "Validation RMSE": -cv_results["test_rmse"],
    "Train R2": cv_results["train_r2"],
    "Validation R2": cv_results["test_r2"],
})

print(results_df)

   Fold  Train MAE  Validation MAE  Train MSE  Validation MSE  Train RMSE  \
0     1   0.211294        0.411572   0.083815        0.380373    0.289508
1     2   0.206443        0.406091   0.085651        0.322324    0.292662
2     3   0.221810        0.322193   0.096295        0.197458    0.310315
3     4   0.203747        0.381999   0.078039        0.294721    0.279355
4     5   0.211110        0.412682   0.084576        0.349381    0.290820

   Validation RMSE  Train R2  Validation R2
0         0.616744  0.852915       0.459158
1         0.567736  0.853815       0.501928
2         0.444363  0.843476       0.622221
3         0.542882  0.872922       0.448045
4         0.591084  0.860279       0.385128

In [ ]:
print("Average Cross-Validation Performance:")
print(f"Mean Train MAE:       {(-cv_results['train_mae']).mean():.2f}")
print(f"Mean Validation MAE:  {(-cv_results['test_mae']).mean():.2f}")
print(f"Mean Train MSE:       {(-cv_results['train_mse']).mean():.2f}")
print(f"Mean Validation MSE:  {(-cv_results['test_mse']).mean():.2f}")
print(f"Mean Train RMSE:      {(-cv_results['train_rmse']).mean():.2f}")
print(f"Mean Validation RMSE: {(-cv_results['test_rmse']).mean():.2f}")
print(f"Mean Train R2:        {cv_results['train_r2'].mean():.4f}")
print(f"Mean Validation R2:   {cv_results['test_r2'].mean():.4f}")

Average Cross-Validation Performance:
Mean Train MAE:       0.21
Mean Validation MAE:  0.39
Mean Train MSE:       0.09
Mean Validation MSE:  0.31
Mean Train RMSE:      0.29
Mean Validation RMSE: 0.55
Mean Train R2:        0.8567
Mean Validation R2:   0.4833

In [ ]:
y_pred_cv = cross_val_predict(
    estimator=rf_model,
    X=X,
    y=y,
    cv=kf,
    n_jobs=-1
)

In [ ]:
mae = mean_absolute_error(y, y_pred_cv)
mse = mean_squared_error(y, y_pred_cv)
rmse = np.sqrt(mse)
r2 = r2_score(y, y_pred_cv)

print("Overall 5-Fold CV Metrics:")
print(f"MAE:  {mae:.2f}")
print(f"MSE:  {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2:   {r2:.4f}")

Overall 5-Fold CV Metrics:
MAE:  0.39
MSE:  0.31
RMSE: 0.56
R2:   0.4835

In [ ]:
rf_model.fit(X, y)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [ ]:
predictions = np.expm1(predictions)

/tmp/ipykernel_615/118988206.py:1: RuntimeWarning: overflow encountered in expm1
  predictions = np.expm1(predictions)

In [ ]:
sample = X.iloc[:5]

predictions = rf_model.predict(sample)
predictions = np.expm1(predictions)

actual = np.expm1(y.iloc[:5])

for i in range(5):
    print(f"Predicted: {predictions[i]:.0f} | Actual: {actual.iloc[i]:.0f}")

Predicted: 79672 | Actual: 79833
Predicted: 153812 | Actual: 260000
Predicted: 95560 | Actual: 109024
Predicted: 19681 | Actual: 20000
Predicted: 153110 | Actual: 150000

In [ ]:
import joblib

joblib.dump(rf_model, "salary_model.pkl")

['salary_model.pkl']

In [ ]:
joblib.dump(X.columns.tolist(), "model_columns.pkl")

['model_columns.pkl']

In [ ]:
model = joblib.load("salary_model.pkl")
columns = joblib.load("model_columns.pkl")

sample = X.iloc[[0]]

prediction = model.predict(sample)
np.expm1(prediction)
print("Prediction:", prediction)

Prediction: [11.2856862]

In [40]:

joblib.dump(top_8_locations, "top_locations.pkl")
joblib.dump(experience_map, "experience_map.pkl")
joblib.dump(size_map, "size_map.pkl")

print("\nArtifacts saved successfully:")

print("- top_locations.pkl")
print("- experience_map.pkl")
print("- size_map.pkl")

Artifacts saved successfully:
- top_locations.pkl
- experience_map.pkl
- size_map.pkl